language: ruby
rvm:
- 2.3.5
cache:
  bundler: true
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: q2ElGeEFkwkqF6/1noOxy+oOxYISsPapi57I4N4ep38HDrk+IzcexaSjypFPlNAPCpFFw/K7DVdsuy3BBiWRG5ylE1dAoVk5Ktq2BauJPaEEOkxQ8QHAXc5N/Ydp5m3tplbDU/7ojCp17hdZWSe0amZLSrPLNB1iSce/oZ+hDFvowBN51iuP0gG9VRSsq1B5kC6+Tiu3jWXMUX266y4VhUKsPItl24ZZPpTP5ap9VbL9tEuLAR4Vfdu/wgeD7n0cxAhaZXOLSul3mvfTvOZkdsRAu0JvRMWptzsE2a7n4ub+3OoeOowDr4i/x+uzGdpOjM/A0zHfifp5vl4/nTwKIbMvNKDL391k5zvEybdlY670/g91TsrC8KBaDBmywjMvn2Ft42qmIfhb2cZlNT0Adr58Bps4L4Bufn21kTBIq8deDgfk/CzR7yeCVZ6SbVpFS7Ha6GJVEAk2ZnSZ0c7EKOQE+qu793fF/6XZU0glIiI9Rp0D2hdtQXDL+788Pc+ZJXHPSA96uB91PlW5+Men0meq6VdDNhtByicLIVgs0WN1yyTePfj2HZwH4yfP8p/+hSzb/Cxd+f2cSAHXkqlpmrsgfPJE2bxFe8uGTppl9/7i9vPaxuRneA7lMlkfbD+MTY1seU+uoYDD8ulK9slMmdajlKnlghDT3Q0xMAHh6xA=
  app: shcoderdojo
  run: rake db:migrate
  on:
    repo: 13gne/shcoderdojo
