language: ruby
rvm:
- 2.3.5
cache:
  bundler: true
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ihQUgTyXJjuOVmgQ69ZHrkOZdtPmLUnb2hOCbQLouwYL8bRYtdchyrWYznSKemTtJ36AdfvixzdREUfO5rlRR5yDKJpGRDHaPpBFnOD+SKFwpSfF+28wdG9Us5b54qKrb+7nsjJmdrY+KMQnig9Ij6w9Q+2FxbqcPb0CqEQbEYeeszdIbMWzICKlJ5N99zIi5fyv8DgeBE/o2MgIdqnRK5nonFnH+qhwxOxvE4WJi1oX9rLe097x/DVpttiTZvGHdrE+E4hIsWw0bgDiTFcRMYs34X/temenvhgkAahVMDVOYlEY/SPMf18St0LxUUVt026wZX48QQko7pAt57LkYzJLlDtDgEtPCWMrTs8LlBYE4lAAu7PRQ6rrNigyLb5Pxsooac3pPLLiBJP/Q6XzYNOIC/WmbWVjZySssJOKiEl/EO7jDXAfmnHpL3PZA2SqarBcCnDoeM17Xs7m8bhm0cQ/GURHIlnhfw1wYFsT5YeUVMcbzwtC+efSOQEaAGVlVCgFgqcDOZ+qOtMpgwWKnRv0sPEPfGlvm+kmQxcDMtdLNtnTjNiBD9cqqVH5zk/0BU6oc/O3+/J7C8VzRecb7zuDaRyMN8tC7yHvg45Y2tM7kb1BaCfIoW4dYVkjIcOzPYLjxtqCE+QrXILvcGZRezX/H+YkwpdrLW9k/AqBDK0=
  app: shcoderdojo
  on:
    repo: 13gne/shcoderdojo
