language: ruby
rvm:
- 2.3.5
cache:
  bundler: true
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: jeTmEHeJiOICOr/ceB3kma84/MJSbietVqNva1IFrLmjI2NPFNnqGrqYLh6UtoT49ltGN7blfM77V/0yYnFTFwFUrxreTOFmejhhzoYR/2LXkBkS5eVhgRWpD1FWDdkC0oKy13ciCbfhX4es6eBddKSJZ1zWDz47aKBhGco9FeRC6KwaGFIE+n2hr+rrM9+vpzz2/VlUXBCqxV4u4PdOxEoPnWaIL90fPKEYdSAY1b9sNcUjhE5ZgDwUIfnW39RMyxlE7oySRq9nkwv5gxRxcLRJQpBkRdaHPyX6W3vMhtBHZGq5tQczsLeTr/0KAnlKR6w+oBn0ktWKLz4fMeXySPysvgb45j+7ihdwez/GJMqmT/JvLIl5L3XSMo40vPr6sC86BPqOX4NHaFr8b+w29LYqf6kg2hM/RWmynEFFf3KHVyq+U26RUvfBl5tu0I0daDtXST9pHbjoAM443swRRKizEr43MsBbi84l3zp9DF1xyo7zorUzeuNLJRtsfvO+GUgIuF/cNye/YAC7nR75/3L0jRkdLSjLnKDvtSeSGhTGWxUnIp2Gm8lqLhKfqYkddgVbiEvhAUKXPmQIXk7KoAVb9Fe02ntLOD68wjYOaJ5kxtmu9gKlx/KYX55jFY4G6bueDEosP8EYZiRpLGEso2s2dP3kpS4ReXrM4Ezo1PU=
  app: shcoderdojo
  on:
    repo: 13gne/shcoderdojo
