language: ruby
rvm:
- 2.3.3
cache:
- bundler
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: RW9x5q7kTc/aRpYbVmRAbsnNrMpjsGjof3FSQVPCMbQGHlGeMGSkSzWzBvFyZQsOXjc6KEU43H9a1d8RWLgS/tjTw/UqLDScR2d1I/nmeOPLeovCckqycPOpoM/lvf9WwL8jeem+mRMAB3oNkzJ3Jna4cJ1twrw0jf7H1rPumt2WFzrn8MC84j5iaKYEpbszdbqKbQ1JFGiEt1Pdu94x50OY9a5OQjWDRdrRLeX61RaGMM0MMhy6VKNYkBiynSuZ/rqJ4cnJlw4EA0zdJQADz8v2zJqbesyXWx57i1SsyJwcZPYZ5+8RMSjdzfwEZAxbAFO9zolm0BTAB9XEf0okcHGhnGJICKs+jfpDAZZXlDs856h1lI2M18G8MTexmxHTzGIVCS/5Fqk8L/pVnz3UxOxTL3NvUXGEPEI7yTL2uHW0s6keGeF0te+MTAmh973OoiBjA6lVV4ZrfpSJngBG82xITavQMNqgDLueHHnCQyQGJKlsNpDhy0MEXXRjJ3CswCI21QfTwFSMzNohKSYImUA8As4jvOcV7t4yKD3aE416+mwXLR/CZzQvcw4uN2FT9N+qNzwpyYgE+nrrwY8vAXv3+U9/l5NUoNMO+bGKbnyH3o0O6rOwZ7dewRXUxUpdEmuBq45OwqkHJnqCDNKVS5UZdSoRyX8azUuWdkODP+M=
  app: shcoderdojo
  on:
    repo: 13gne/shcoderdojo
