language: ruby
rvm:
- 2.3.5
cache:
  bundler: true
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Fa2gSmA/1hPFTkn+520fCIC7NQODF6lor1r4qqNrvMV+5RHnil6wJZ/xgZ1E8Qq6ihd0l01EfByBmIsVn/obHKWcUhnoeHn/24QW3XVpygU7OjGv+H0enmD9sk/AeMaEUq2eiyxrk22luTMw/Ip0ogWMedBnpG6B7Ucf6v8NrATaJtlMe/ST/Dd7Zn3MVuCdby8MWVX0qysp+DnXfvHx0t9LtU7baln2Wn5cY1kaGmmTKQc70pe4FEAs7E/Yg0PndCob41WQKlN/SEEucQeMf8ciThj+LFgw2MPnQyGFm1ouigk6zSWeoKZH3Hpjka2v2+ir57y8IFMrBbejMRs2wri6PbZ33h0NA3OCaNSmhkl6jRNUKP17V/z9PHf29Kq5CySHaW5jzY5k+5+UHTl/q7d9tqZV7dgfBzh/WRKVbiVtbqloHSMpnsg7/765TbNs6GcIDTOyD3N71JdNTi08YWksinF2OXiyLI9z7H13E4fd/ShE+Zt0p82A2i6eh6HoiSETcYXOJJNo3ca2gV9vsp/YBpIQ3Va0gZUJRyItuVQgkZ8XF9PDXaWzEvYIZtKgUGjT2sUZTYKRsvwIGcOXDhBpJqyDi426v4+QeSnz53E4ShcKEYcEKxEdv2unFGwXhbDx17Wru0Y8WBu3eG6vGEvrLJRL4Np4HgNjvMeRsSI=
  app: shcoderdojo
  on:
    repo: 13gne/shcoderdojo
