source 'https://rubygems.org'
ruby '2.3.5'
gem 'rails', '5.2.0'
gem 'bootsnap'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'bootstrap-sass'
gem 'devise'
gem 'figaro'
gem 'high_voltage'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'sendgrid'
gem 'simple_form'
gem 'raygun4ruby'
gem 'haml'
gem 'haml-rails'
gem 'wysiwyg-rails'
gem 'ransack'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
  gem 'annotate'
  gem 'web-console'
  gem 'spring'
  gem 'rails-erd'
  gem 'listen'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
end
group :development, :test do
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end
group :production do
  gem 'rails_12factor'
end
